Support for reading codereg of metadata 27.1
djkaty/Il2CppInspector pull request #139
Opened 2021-02-13 22:54 UTC by SamboyCoding

Adds support for the "Adjustor Thunks" used in metadata version 27.1 (Unity 2020.2.4), sets the image version to 27.1 if they're detected, and adjusts the location of the detected codereg struct accordingly.

Does not include updated Unity headers, so the app crashes with a fatal error once the binary read completes, due to them being missing.

2021-02-15 14:10 UTC, djkaty requested changes
Seems fine, I'm going to note this doesn't actually add 'support' rather 'compatibility' because the adjustorThunks are not output in IDA/Ghidra/JSON or included in the AppModel. That being said, since I know exactly how to fix that quickly it's probably faster for everyone if I just add it in after merging this :)

2021-02-15 14:10 UTC, djkaty commented on Il2CppInspector.Common/IL2CPP/Il2CppBinaryClasses.cs
> +        [Version(Min = 27.1)] public long adjustorThunkCount;
Code style - attribute on separate line (and in the other instances below)

2021-02-15 14:10 UTC, djkaty commented on Il2CppInspector.Common/IL2CPP/ImageScan.cs
> +                    //If reversePInvokeWrapperCount is a pointer, then it's because we're actually on 27.1 and there's a genericAdjustorThunks pointer interfering.
Code style - space after double-dash

2021-02-15 14:23 UTC, SamboyCoding commented
Feedback addressed

2021-02-16 11:48 UTC, merged

2021-02-16 11:48 UTC, djkaty commented
Confirmed working with compiled 2020.4 apps when rebased onto latest commit with updated Unity headers. Thank you for your contribution!