Add MethodInfo to C++ scaffolding output
djkaty/Il2CppInspector pull request #84
Opened 2020-09-25 18:50 UTC by Warpten

I recently needed to access static properties of a type for which no `TypeInfo` was present, however `MethodInfo` was there and analysis of the game in IDA showed that passing a proper MethodInfo pointer was necessary. Hence this pull request.

Let me know of there's anything to change (code style, naming, moving these pointers to another header file, etc)

Cheers

2020-09-25 20:33 UTC, Warpten commented
Oops, noticed just now this can't ... very easily work because some types actually live in `app`

2020-10-13 07:01 UTC, djkaty requested changes
Sorry for the late reply. Excellent idea to include the MethodInfo pointers. I've left a couple of comments.

There is a small issue whereby there is no name conflict checking for if an existing label with the given method name + "__MethodInfo" already exists, but for the sake of such a minor edge case I'm happy to merge this when the items noted have been addressed and deal with it later.

Thank you!

2020-10-13 12:18 UTC, Warpten commented on Il2CppInspector.Common/Properties/Resources.resx
> +#define DO_APP_FUNC_INFO(a, n) extern struct MethodInfo * n
Yep sorry, I fixed that locally and never forced pushed. It's a bad habit I have to forget to spam Ctrl+S.

2020-10-13 12:23 UTC, Warpten commented
I kind of attempted to make an higher level "true" C++ code generation, but it gets messy really quick with nested types.

On another subject completely unrelated to this pull request, is the layout of objects with inheritance valid in IDA? For example, in game <insert unity game that recently blew up and for which I'm making a discord bot>, a lot of types inherit from some other types, but at the very least hexrays's output of it seems completely shifted (as if the base `__Fields` has bad size), and thus the offset at which fields are defined in structs does not match what is printed out in the c# synopsis.

In any case, I'll fix the glaring issues later today

2020-10-13 12:25 UTC, Warpten commented on Il2CppInspector.Common/Outputs/CppScaffolding.cs
> +                    var arguments = string.Join(", ",
I blame resharper. WIll fix.

2020-10-13 17:14 UTC, Warpten commented
That should be all you asked for. No idea how to mark change requests as resolved, I rarely do pull requests.

Please let me know if there's anything else that needs adjusting.

Cheers!

2020-10-13 17:49 UTC, djkaty commented
I'll check the changes after work but here is a quick reply to your other points in the meantime!

Quick question: These new values are actually MethodInfo** (pointers to pointers) right? ie. you would call a method with `*Foo__MethodInfo` (with the pointer indirection asterisk) as the final argument?

> I kind of attempted to make an higher level "true" C++ code generation, but it gets messy really quick with nested types.

This is on the roadmap for the undetermined future and is commonly requested. The Il2CppInspector 2020.2 release was the first iteration of the C++ scaffolding - the idea was to just make it work at all (virtually just a proof of concept), it requires a lot of work and there's a long list of todo items. Hopefully as we iterate on it over the coming months and years it will become more polished and complete.

> On another subject completely unrelated to this pull request, is the layout of objects with inheritance valid in IDA? For example, in game <insert unity game that recently blew up and for which I'm making a discord bot>, a lot of types inherit from some other types, but at the very least hexrays's output of it seems completely shifted (as if the base `__Fields` has bad size), and thus the offset at which fields are defined in structs does not match what is printed out in the c# synopsis.

We make a fairly strong effort to ensure the offsets are correct, with the generated type headers tuned both for MSVC and GCC binaries, and for the individual version of Unity. Quite a lot of work went into that actually so if there is a bug it would be great if you could open a new issue with as much detail as possible (or a PR if you can fix it) and I'll gladly take a look!

2020-10-14 07:02 UTC, Warpten commented
> Quick question: These new values are actually MethodInfo** (pointers to pointers) right? ie. you would call a method with *Foo__MethodInfo (with the pointer indirection asterisk) as the final argument?

If my memory serves me right (I actually haven't touched that project since last week, and I'm kind of reluctant to do so now with the recent updates), no, they are pointers to `MethodInfo`. My understanding is that `MethodInfoPtrAddress` is the address of `MethodInfo` itself, not some pointer to it, as I think IDA corroborates. In my testing, that seemed to work, but I did not try to inspect the `MethodInfo` objects to make sure I was reading actual data.

I'll doublecheck tonight (hazy memory), because if there's a double indirection, then my code is wrong.

2020-11-24 12:58 UTC, djkaty commented
I finally got a chance to look into this.

The `__MethodInfo` items are indeed double-indirected. With your existing code, this crashes:

```cpp
        auto emptyArray = Array_Empty_12(Array_Empty__MethodInfo);
        std::cout << "Empty array max_length: " << emptyArray->max_length << std::endl;
```

but this works:

```cpp
        auto emptyArray = Array_Empty_12(*(MethodInfo **) Array_Empty__MethodInfo);
        std::cout << "Empty array max_length: " << emptyArray->max_length << std::endl;
```

I have changed the code in the PR to set the types as `MethodInfo **` and now the following code will work as intended:

```cpp
        auto emptyArray = Array_Empty_12(*Array_Empty__MethodInfo);
        std::cout << "Empty array max_length: " << emptyArray->max_length << std::endl;
```

I will merge your PR and add an extra commit with this fix 🙂

2020-11-24 12:59 UTC, merged

2020-12-08 23:39 UTC, Warpten commented
Sorry, I completely forgot about this PR. Thanks for taking the time to look into it in my stead.

2020-12-09 00:22 UTC, djkaty commented
No problem, I hope it proves useful to someone 🙂